name: Docker image (Java)

on:
  push:
    branches:
      - master
    paths:
      - '**/ci-java.yml'
      - 'java.Dockerfile'
      - 'java.entrypoint.sh'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  java:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [11, 17, 21, 22, 23, 24]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497 # v6
        with:
          build-args: JAVA_VERSION=${{ matrix.java_version }}
          context: .
          file: java.Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: djoh/all-in-one:java${{ matrix.java_version }}
          cache-from: type=registry,ref=djoh/all-in-one:buildcache_java${{ matrix.java_version }}
          cache-to: type=registry,ref=djoh/all-in-one:buildcache_java${{ matrix.java_version }},mode=max
